IMAGE_NAME = "madinasoc2030/pfsense"

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = IMAGE_NAME
  config.ssh.shell = "sh"
  config.ssh.insert_key = false 
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # to access pfSense on http://localhost:8081
  config.vm.network :forwarded_port, guest: 80, host: 8081, host_ip: "127.0.0.1"

  # Internal LAN config
  config.vm.network "private_network", 
  auto_config: false,
  virtualbox__intnet: "zabbix"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "pfsense-box"
  end

end